urls.py
from django.conf.urls.defaults import patterns, include, url
from kokous.views import generalViews, profileViews, meetingViews, apiViews, miscViews

#enables admin
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	
	# Kokous Views
	# General Views
	url(r'^$', generalViews.home),
	url(r'^signup/$', generalViews.signup),
	url(r'^login/$', generalViews.login),
	url(r'^logout/$', generalViews.logout),
	
	# Profile Views
	url(r'^profile/$', profileViews.profile),
	url(r'^user/(\d*)$', profileViews.user),
	url(r'^settings/$', profileViews.settings),
	
	# Meeting Views
	url(r'^meetings/$', meetingViews.meetings),
	url(r'^meeting/(\d*)$', meetingViews.viewMeeting),
	url(r'^meeting/create/$', meetingViews.createMeeting),
	url(r'^meeting/edit/(\d*)$', meetingViews.editMeeting),
	url(r'^meeting/finalize/(\d*)$', meetingViews.finalizeMeeting),
	url(r'^meeting/rsvp/(\d*)$', meetingViews.rsvpMeeting),
	url(r'^meeting/comment/create/(\d*)$', meetingViews.createComment),

	# API Views
	url(r'^api/([a-z]*).json$', apiViews.api),

	# Misc Views
	url(r'^about/', miscViews.misc),
	url(r'^blog/', miscViews.misc),
	url(r'^contact/', miscViews.misc),
	url(r'^TOS/', miscViews.misc),
	url(r'^resources/', miscViews.misc),
	url(r'^privacy/', miscViews.misc),
	
	# Admin
    url(r'^admin/', include(admin.site.urls)),
)


import settings
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
)

kokous/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):  
	user = models.OneToOneField(User)
	bio = models.TextField(blank=True)
	avatar = models.ImageField(blank=True, upload_to='avatars/')
	
	def __unicode__(self):
		return self.user.username

class UserOAuth(models.Model):
	user = models.OneToOneField(User)
	OAuthKey = models.CharField(max_length=40)

class Meeting(models.Model):
	members = models.ManyToManyField(User, through='UserMeeting')
	title = models.CharField(max_length=255)
	description = models.TextField()
	discussions = models.TextField(blank=True)
	conclusions = models.TextField(blank=True)
	created_date_time = models.DateTimeField()
	meeting_date = models.DateField()
	start_time = models.TimeField()
	end_time = models.TimeField()
	location = models.CharField(max_length=255, blank=True)
	
	def __unicode__(self):
		return self.title
		
	class Meta:
		ordering = ['-meeting_date', 'start_time']

class UserMeeting(models.Model):
	user = models.ForeignKey(User)
	meeting = models.ForeignKey(Meeting)
	is_Admin = models.BooleanField()
	actions = models.TextField(blank=True)
	notified = models.BooleanField(default=False)
	completedActions = models.BooleanField(default=False)
	RSVP_CHOICES = (
		(0, 'Has not replied'),
		(1, 'Attending'),
		(2, 'Not Attending'),
		(3, 'Maybe Attending'),
	)
	rsvp_status = models.IntegerField(choices=RSVP_CHOICES, default=0)

class Comment(models.Model):
	user = models.ForeignKey(User)
	meeting = models.ForeignKey(Meeting)
	text = models.TextField()
	created_date_time = models.DateTimeField()

	class Meta:
		ordering = ['created_date_time']

kokous/views/apiViews.py
from __init__ import *
from django.core import serializers

def api(request, resource):
	if request.method == 'GET':
		id = request.GET.get('id', '')
		query = request.GET.get('query', '')
		if resource == 'meeting' : return meetingResource(request, id)
		if resource == 'user' : return userResource(request, query)


def meetingResource(request, userId):
	if request.user.id == int(userId):
		return HttpResponse(serializers.serialize("json", request.user.meeting_set.all()))
	else:
		return HttpResponse(json.dumps({'API_ERROR': 'FORBIDDEN'}))

def userResource(request, query):
	userObjects = User.objects.filter( Q(first_name__icontains=query) | Q(last_name__icontains=query)
										| Q(username__icontains=query) ).exclude(id=request.user.id)
	users = []
	if query:
		for userObject in userObjects:
			users.append( {'first_name': userObject.first_name, 'last_name': userObject.last_name, 'username': userObject.username} )
	print users
	print HttpResponse(json.dumps(users, cls=DjangoJSONEncoder))
	return 	HttpResponse(json.dumps(users, cls=DjangoJSONEncoder))
	

kokous/views/generalViews.py
from __init__ import *

def home(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect('/profile/')
	else:
		c = {}
		c.update(csrf(request))
		c.update({'loginForm': LoginForm(), 'signupForm': SignupForm()})
		return render_to_response('index.html', c, context_instance=RequestContext(request))

def signup(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect('/profile/') # if user is already signed up, redirect to profile
	c = {}
	c.update(csrf(request))

	if request.method != 'POST':
		signupForm = SignupForm()

	else:
		signupForm = SignupForm(request.POST)
		if signupForm.is_valid():
			cleaned_data = signupForm.cleaned_data
				
			# Creating user
			new_user = User.objects.create_user(username=cleaned_data['username'], email=cleaned_data['email_address'])

			new_user.first_name=cleaned_data['first_name'].capitalize() # Django doesn't do that for you!
			new_user.last_name=cleaned_data['last_name'].capitalize()
			new_user.set_password(cleaned_data['password'])
			new_user.save()
			
			# Creating user profile
			userProfile = UserProfile(user=new_user)
			userProfile.save()
			
			# Logging him in
			user = auth.authenticate(username=cleaned_data['username'], password=cleaned_data['password'])
			auth.login(request, user)
				
			return HttpResponseRedirect('/profile/')
				
	c.update({'signupForm' : signupForm})
	return render_to_response('signup.html', c, context_instance=RequestContext(request))

def login(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect('/profile/') # if user is already signed up, redirect to profile

	if request.method != 'POST':
		loginForm = LoginForm()

	else:
		loginForm = LoginForm(request.POST)
		if loginForm.is_valid():
			user = auth.authenticate(username=loginForm.cleaned_data['username'], password=loginForm.cleaned_data['password'])
			auth.login(request, user)
			return HttpResponseRedirect('/profile/')

	c = {}
	c.update(csrf(request))
	c.update({'loginForm' : loginForm})
	return render_to_response('login.html', c, context_instance=RequestContext(request))

def logout(request):
	auth.logout(request)
	return HttpResponseRedirect("/")

kokous/views/meetingViews.py
from __init__ import *

def createMeeting(request):
	if not request.user.is_authenticated():
		return HttpResponseForbidden("<h1>Forbidden</h1><p>user not authenticated</p>")

	c={}
	c.update(csrf(request))
	if request.method == 'POST':
		meetingForm = MeetingForm(request.POST)
		if meetingForm.is_valid():
			membersText=meetingForm.cleaned_data['participants']

			users=[request.user]
			usernames=membersText.split(",")
			for username in usernames:
				user=User.objects.get(username=username)
				users.append(user)
				
			meeting = Meeting.objects.create(title=meetingForm.cleaned_data['title'], 
											description=meetingForm.cleaned_data['description'], 
											created_date_time=datetime.now(), 
											meeting_date=meetingForm.cleaned_data['meeting_date'],
											start_time=meetingForm.cleaned_data['start_time'],
											end_time=meetingForm.cleaned_data['end_time'],
											location=meetingForm.cleaned_data['location'])
			for user in users:
				if user is request.user:
					userMeeting = UserMeeting(user=user,
											meeting=meeting,
											is_Admin=True)
				else:
					userMeeting = UserMeeting(user=user,
											meeting=meeting,
											is_Admin=False)
				userMeeting.save()
			return HttpResponseRedirect("/meetings/")

	else:
		meetingForm = MeetingForm()

	c.update({'meetingForm': meetingForm, 'sections': sections, 'sectionTitle': 'Create Meeting'})
	return render_to_response('createMeeting.html', c, context_instance=RequestContext(request))

def meetings(request):
	if not request.user.is_authenticated():
		return HttpResponseForbidden("<h1>Forbidden</h1><p>user not authenticated</p>")
	
	meetings = request.user.meeting_set.all()	
	c={}
	c.update({'sectionTitle': inspect.stack()[0][3], 'sections': sections, 'meetings': meetings})
	return render_to_response('meetings.html', c, context_instance=RequestContext(request))

def viewMeeting(request, meetingId):
	if not request.user.is_authenticated():
		return HttpResponseForbidden("<h1>Forbidden</h1><p>user not authenticated</p>")
	
	try:
		meeting = Meeting.objects.get(id=meetingId)
		
	except Meeting.DoesNotExist:
		raise Http404
		
	else:
		try:
			userMeeting = UserMeeting.objects.get(user=request.user, meeting=meeting)

		except UserMeeting.DoesNotExist:
			return HttpResponseForbidden("<h1>Forbidden</h1><p>user not authenticated</p>")

		else:					
			c={}
			c.update(csrf(request))
			c.update({'meeting': meeting, 'isAdmin': userMeeting.is_Admin,
					'userMeetings': UserMeeting.objects.filter(meeting=meeting),
					'rsvpForm': RSVPForm(initial={'rsvp_choice': userMeeting.rsvp_status}),
					'commentForm': CommentForm(), 'sections': sections})
			
			rsvp_choices = ['haveNotRepliedMembersUserMeetings', 'attendingMembersUserMeetings',
							'maybeAttendingMembersUserMeetings', 'notAttendingMembersUserMeetings']
			for index, choice in enumerate(rsvp_choices):
				c.update( {choice: UserMeeting.objects.filter(meeting=meeting, rsvp_status=index)} )
			
			return render_to_response('meeting.html', c, context_instance=RequestContext(request))

def editMeeting(request, meetingId):
	try:
		meeting = Meeting.objects.get(id=meetingId)
		
	except Meeting.DoesNotExist:
		raise Http404

	try:
		userMeeting = UserMeeting.objects.get(user=request.user, meeting=meeting)

	except UserMeeting.DoesNotExist:
		return HttpResponseForbidden("<h1>Forbidden</h1><p>user not authenticated</p>")
	
	if not userMeeting.is_Admin:
		return HttpResponseForbidden("<h1>Forbidden</h1><p>user is not admin to meeting</p>")
		
	if request.method != 'POST':
		participants = []
		for member in meeting.members.all():
			if member != request.user:
				participants.append(member.username)
		
		meetingForm = MeetingForm(initial={'title': meeting.title, 'meeting_date': meeting.meeting_date,
											'start_time': meeting.start_time.strftime("%I:%M %p"), 'end_time': meeting.end_time.strftime("%I:%M %p"),
											'participants': ','.join(participants), 'location': meeting.location,
											'description': meeting.description})
											
	else:
		meetingForm = MeetingForm(request.POST)
		if meetingForm.is_valid():
			membersText=meetingForm.cleaned_data['participants']

			newUsers=[request.user]
			usernames=membersText.split(",")
			for username in usernames:
				user=User.objects.get(username=username)
				newUsers.append(user)

			meeting.title=meetingForm.cleaned_data['title']
			meeting.description=meetingForm.cleaned_data['description']
			meeting.meeting_date=meetingForm.cleaned_data['meeting_date']
			meeting.start_time=meetingForm.cleaned_data['start_time']
			meeting.end_time=meetingForm.cleaned_data['end_time']
			meeting.location=meetingForm.cleaned_data['location']

			meeting.save()
		
			# Deleting old users that were in the meeting, and are now removed
			oldUsers = []
			for userMeeting in UserMeeting.objects.filter(meeting=meeting):
				oldUsers.append(userMeeting.user)
			
			indexesToDelete = []
			for index, oldUser in enumerate(oldUsers):
				if oldUser in newUsers:
					indexesToDelete.append(index)

			indexesToDelete.reverse()
			for index in indexesToDelete:
				del oldUsers[index]
			
			for oldUser in oldUsers:
				UserMeeting.objects.get(user=oldUser, meeting=meeting).delete()
			#######################################################################
			
			for user in newUsers:
				try:
					userMeeting = UserMeeting.objects.get(user=user, meeting=meeting) # existing users in the meeting
				except UserMeeting.DoesNotExist: # create the usermeeting	
					userMeeting = UserMeeting(user=user,
											meeting=meeting,
											is_Admin=False)
					userMeeting.save()					
				else:
					pass # user already exists, carry on
					
			return HttpResponseRedirect("/meeting/%s" % meetingId)		

	c = {}
	c.update(csrf(request))
	c.update({'meetingForm': meetingForm,  'meetingId': meetingId, 'sectionTitle': 'Edit Meeting',  'sections': sections})
	return render_to_response('editMeeting.html', c, context_instance=RequestContext(request))


def finalizeMeeting(request, meetingId):
	try:
		meeting = Meeting.objects.get(id=meetingId)
		
	except Meeting.DoesNotExist:
		raise Http404

	try:
		userMeeting = UserMeeting.objects.get(user=request.user, meeting=meeting)

	except UserMeeting.DoesNotExist:
		return HttpResponseForbidden("<h1>Forbidden</h1><p>user not authenticated</p>")
	
	if not userMeeting.is_Admin:
		return HttpResponseForbidden("<h1>Forbidden</h1><p>user is not admin to meeting</p>")
			
	ActionFormSet = formset_factory(ActionForm, extra=0)
	
	if request.method != 'POST':
		finalizeForm = FinalizeForm(initial={'discussions': meeting.discussions, 'conclusions': meeting.conclusions})

		initialFormData = []
		for tmpUserMeeting in UserMeeting.objects.filter(meeting=meeting):
			initialFormData.append({'actions': tmpUserMeeting.actions,
									'completedActions': tmpUserMeeting.completedActions,
									'userId': str(tmpUserMeeting.user.id),
									'name': '%s %s' % (tmpUserMeeting.user.first_name, tmpUserMeeting.user.last_name)})

		actionFormSet = ActionFormSet(initial=initialFormData)
		
	else:
		finalizeForm = FinalizeForm(request.POST)
		actionFormSet = ActionFormSet(request.POST)
		
		if finalizeForm.is_valid() and actionFormSet.is_valid():
			meeting.discussions=finalizeForm.cleaned_data['discussions']
			meeting.conclusions=finalizeForm.cleaned_data['conclusions']
			meeting.save()
			
			for actionForm in actionFormSet:
				userMeeting = UserMeeting.objects.get(user__id=int(actionForm.cleaned_data['userId']), meeting=meeting)
				userMeeting.actions = actionForm.cleaned_data['actions']
				userMeeting.completedActions = actionForm.cleaned_data['completedActions']
				userMeeting.save()
				
			return HttpResponseRedirect('/meeting/%s' % meetingId)

	c = {}
	c.update(csrf(request))
	c.update({'finalizeForm': finalizeForm, 'actionFormSet': actionFormSet, 'meetingId': meetingId,
			'sectionTitle': 'Finalize Meeting', 'sections': sections})
	return render_to_response('finalizeMeeting.html', c, context_instance=RequestContext(request))


def rsvpMeeting(request, meetingId):
	if not request.user.is_authenticated():
		return HttpResponseForbidden("<h1>Forbidden</h1><p>user not authenticated</p>")
	
	try:
		meeting = Meeting.objects.get(id=meetingId)
		
	except Meeting.DoesNotExist:
		raise Http404
		
	else:
		try:
			userMeeting = UserMeeting.objects.get(user=request.user, meeting=meeting)

		except UserMeeting.DoesNotExist:
			return HttpResponseForbidden("<h1>Forbidden</h1><p>user not authenticated</p>")
			
	if request.method != 'POST':
		return HttpResponseForbidden("<h1>Forbidden</h1><p>POST requests only</p>")
	else:
		rsvpForm = RSVPForm(request.POST)
		if rsvpForm.is_valid():
			userMeeting.rsvp_status = rsvpForm.cleaned_data['rsvp_choice']
			userMeeting.save()
			return HttpResponseRedirect('/meeting/%s' % meetingId)
	
def createComment(request, meetingId):
	if not request.user.is_authenticated():
		return HttpResponseForbidden("<h1>Forbidden</h1><p>user not authenticated</p>")

	try:
		meeting = Meeting.objects.get(id=meetingId)

	except Meeting.DoesNotExist:
		raise Http404

	else:
		try:
			userMeeting = UserMeeting.objects.get(user=request.user, meeting=meeting)

		except UserMeeting.DoesNotExist:
			return HttpResponseForbidden("<h1>Forbidden</h1><p>user not authenticated</p>")

	if request.method != 'POST':
		commentForm = CommentForm()
	else:
		commentForm = CommentForm(request.POST)
		if commentForm.is_valid():
			comment = Comment(user=request.user, meeting=meeting,
							text=commentForm.cleaned_data['text'], created_date_time=datetime.now())
			comment.save()
			return HttpResponseRedirect('/meeting/%s' % meetingId)
	c = {}
	c.update(csrf(request))
	c.update({'commentForm': commentForm, 'meetingId': meetingId,
			'sections': sections})
	return render_to_response('createComment.html', c, context_instance=RequestContext(request))

kokous/views/miscViews.py
from __init__ import *

def misc(request):
	return render_to_response("misc.html", context_instance=RequestContext(request))

kokous/templates/meetingTemplates/createComment.html
{% extends "baseTemplates/baseUser.html" %}
{% block sectionContent %}
<form action="/meeting/comment/create/{{ meetingId }}" method="post">{% csrf_token %}
<table>
	<h1>Add a Comment</h1>
	<tr>
		<td>
		{{ commentForm.text }}
		{{ commentForm.text.errors }}
		</td>
	</tr>
</table>
<div class="row">
	<div class="tableFormElem">
		<button class="btn primary" type="submit">Post Comment</button>
		<a href="/meeting/{{ meetingId }}"><button class="btn">Cancel</button></a>
	</div>
</div>
</form>
{% endblock %}

kokous/templates/meetingTemplates/finalizeMeeting.html
{% extends "baseTemplates/baseUser.html" %}

{% block sectionContent %}
<form action="/meeting/finalize/{{ meetingId }}" method="post" >{% csrf_token %} {{ actionFormSet.management_form }}
	<table>
		<tr>
			<th>Discussions</th>
			<td>
				<div class="clearfix tableFormElem">
				{{ finalizeForm.discussions }}
				</div>
			</td>
		</tr>
		<tr>
			<th>Conclusions</th>
			<td>
				<div class="clearfix tableFormElem">
				{{ finalizeForm.conclusions }}
				</div>
			</td>
		</tr>
		
		{% for form in actionFormSet.forms %}
		<tr>
			<th>{{ form.name.value }}'s Actions</th>
			<td>
				<div class="clearfix tableFormElem">
				{{ form.actions }}<br />
				{{ form.completedActions }}
				<span>Completed Action</span>
				{{ form.userId }}
				{{ form.name }}
				</div>
			</td>
		</tr>
		{% endfor %}
	</table>
	
	<div class="row">
		<div class="offset6">
			<button class="btn primary" type="submit">Save</button>
			<a href='/meeting/{{ meetingId }}'><button class="btn">Cancel</button></a>
		</div>
	</div>
</form>
{% endblock %}

kokous/templates/meetingTemplates/meeting.html
{% extends 'baseTemplates/baseUser.html' %}
{% load humanize %}
{% block title %}{{ meeting.title }}{% endblock %}

{% block extraHead %}
<script src="/static/js/jquery1.6.2.js" type="text/javascript"></script>
<script src="/static/js/toggle.js" type="text/javascript"></script>
{% endblock %}

{% block sectionContent %}
<div id="tableSection">
<table class="bordered-table zebra-striped">
	<h1>{{ meeting.title }}</h1>
		<tr>
			<th style="width:100px">Description</th>
			<td>{{ meeting.description|linebreaks }}</td>
		</tr>
		<tr>
			<th>Date</th>
			<td>{{ meeting.meeting_date|naturalday|capfirst }}</td>
		</tr>
		<tr>
			<th>Time</th>
			<td>{{ meeting.start_time|time:"h:i A" }} - {{ meeting.end_time|time:"h:i A" }}</td>
		</tr>
		<tr>
			<th>Participants</th>
		</tr>
		<tr>
			<th>Attending</th>
			<td>
				{% for userMeeting in attendingMembersUserMeetings %}
					<a href="/user/{{ userMeeting.user.id }}">{{ userMeeting.user.username }}</a>{% if not forloop.last %}, {% endif %}
				{% endfor %}
			</td>
		</tr>
		<tr>
			<th>Maybe Attending</th>
			<td>
				{% for userMeeting in notAttendingMembersUserMeetings %}
					<a href="/user/{{ userMeeting.user.id }}">{{ userMeeting.user.username }}</a>{% if not forloop.last %}, {% endif %}
				{% endfor %}
			</td>
		</tr>
		<tr>
			<th>Not Attending</th>
			<td>
				{% for userMeeting in maybeAttendingMembersUserMeetings %}
					<a href="/user/{{ userMeeting.user.id }}">{{ userMeeting.user.username }}</a>{% if not forloop.last %}, {% endif %}
				{% endfor %}
			</td>
		</tr>
		<tr>
			<th>Have not responded</th>
			<td>
				{% for userMeeting in haveNotRepliedMembersUserMeetings %}
					<a href="/user/{{ userMeeting.user.id }}">{{ userMeeting.user.username }}</a>{% if not forloop.last %}, {% endif %}
				{% endfor %}
			</td>
		</tr>

		<tr>
			<th>Discussions</th>
			<td>
				{{ meeting.discussions|default:"<i>no discussions have been added yet.</i>"|linebreaks }}
			</td>
		</tr>
		<tr>
			<th>Conclusions</th>
			<td>
				{{ meeting.conclusions|default:"<i>no conclusions have been added yet.</i>"|linebreaks }}
			</td>
		</tr>
			<th>Location</th>
			<td>
				{% if meeting.location %}
				<img src="http://maps.googleapis.com/maps/api/staticmap?sensor=false&maptype=roadmap&zoom=15&size=250x250&center={{ meeting.location }}&markers=color:red|{{ meeting.location }}" />
				{% else %}
				<i>location not specified.</i>"
				{% endif %}
			</td>
		</tr>
</table>

{% if isAdmin %}
<a href="/meeting/edit/{{ meeting.id }}"><button class="btn primary" type="submit" name="createMeeting">Edit Meeting</button></a>
<a href="/meeting/finalize/{{ meeting.id }}"><button class="btn" type="submit" name="createMeeting">Finalize Meeting</button></a>
{% endif %}
</div>
<br />

<table>
	<h1>Actions</h1>
	<thead>
		<tr>
		<th><h3>User</h3></th>
		<th><h3>Action</h3></th>
		<th><h3>Completed</h3></th>
		</tr>												
	</thead>
	
	{% for userMeeting in userMeetings %}
	<tr>
		<td>
			<h4>{{ userMeeting.user.username }}</h4>
		</td>
		<td>
			{{ userMeeting.actions|default:"<i> user doesn't have any actions to do.</i>"|linebreaks }}
		</td>
		<td>
			{% if userMeeting.completedActions %}<h3>&#10004;</h3>{% else %}<h3>&#x2717;</h3>{% endif %}
		</td>
	<tr>
	{% endfor %}
</table>

<form action="/meeting/rsvp/{{ meeting.id }}" method="post">{% csrf_token %}
<table>
	<h1>RSVP</h1>
	<tr>
		<td>
		{{ rsvpForm.rsvp_choice }}
		<button class="btn primary" type="submit">Save</button>
		</td>
	</tr>
</table>
</form>

<input class="btn action primary" type="button" id="toggle" value="Show Comments"/></br></br>
<div class="panel">
	<table>
	{% for comment in meeting.comment_set.all %}
	<tr>
		<th>
		{% if comment.user.userprofile.avatar %}<img src="{{ comment.user.userprofile.avatar.url }}" width='40' height='40'/>
		{% else %}<img src="/static/avatars/def.png" width='40' height='40'/>{% endif %}
		By {{ comment.user.username }} on {{ comment.created_date_time|date:"M j \a\t g:i A:" }}</th>
	</tr>
	<tr>
		<td>{{ comment.text }}</td>
	<tr>
	{% empty %}
	<i>no comments to date.</i>
	{% endfor %}
	</table>

	<form action="/meeting/comment/create/{{ meeting.id }}" method="post">{% csrf_token %}
	<table>
		<h1>Add a Comment</h1>
		<tr>
			<td>
			{{ commentForm.text }}
			</td>
		</tr>
	</table>
	<div class="row">
		<div class="tableFormElem">
			<button class="btn primary" type="submit">Post Comment</button>
		</div>
	</div>
	</form>
	<br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
</div>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
{% endblock %}

{% block footer %}{% endblock %}

kokous/templates/meetingTemplates/meetings.html
{% extends "baseTemplates/baseUser.html" %}
{% load humanize %}

{% block extraHead %}
<!-- Extra CSS -->
<link rel="stylesheet" href="/static/css/jQueryCSS/general.css" type="text/css" />

<!-- Extra js -->
<script src="/static/js/jquery1.6.2.js" type="text/javascript"></script>
<script src="/static/js/meetingPopup.js" type="text/javascript"></script>
{% endblock %}

{% block sectionContent %}
<div class="clearfix">
	<a href="/meeting/create/" class="btn primary">New Meeting</a>
</div><br>
<table class="bordered-table zebra-striped">
	<thead>
		<tr>
		<th>Title</th>
		<th>Description</th>
		<th>Date</th>
		<th>Starts At</th>
		<th>Ends At</th>
		<th>Participants</th>
		<th>Admin</th>
		</tr>												
	</thead>
	<tbody>
		{% if meetings %}
		{% for meeting in meetings %}
		<td>{{ meeting.title }} <br/><a meetingID="{{ meeting.id }}" class="viewMeeting">View Meeting</a> | <a href="/meeting/{{ meeting.id }}">permalink</a></td>
		<!-- <td>{{ meeting.title }} <br/>(<a href="/meeting/{{ meeting.id }}">View Meeting</a>)</td> -->
		<td>{{ meeting.description|truncatewords:10|linebreaks }}</td>
		<td>{{ meeting.meeting_date|naturalday|capfirst }}</td>
		<td>{{ meeting.start_time|time:"h:i A" }}</td>
		<td>{{ meeting.end_time|time:"h:i A" }}</td>
		<td>
			{% for member in meeting.members.all %}
			<a href="/user/{{ member.id }}">{% ifequal member.id user.id %}you{% else %}{{ member }}{% endifequal %}</a>{% if not forloop.last %}, {% endif %}
			{% endfor %}
		</td>
		<td>
			{% for userMeeting in meeting.usermeeting_set.all %}
			{% ifequal user userMeeting.user %}
				{% if userMeeting.is_Admin %}<h3>&#10004;</h3>{% else %}<h3>&#x2717;</h3>{% endif %}
			{% endifequal %}
			{% endfor %}
		</td>
		</tr>
		{% endfor %}
		{% else %}
		<tr><td colspan=7><i>You don't have any new meetings.</i></td></tr>
		{% endif %}																			
	</tbody>
</table>

<!-- Necessary for popup -->
<div id="popupMeetingInfo">
	<div id="page"></div>
</div>
<div id="backgroundPopup">
</div>

{% endblock %}